//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.3625
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// 此原始程式碼由 wsdl 版本=2.0.50727.42 自動產生。
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="GT_CharacterInfoSoap", Namespace="http://tempuri.org/")]
public partial class GT_CharacterInfo : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback GetGameAccountOperationCompleted;
    
    /// <remarks/>
    public GT_CharacterInfo() {
        this.Url = "http://10.100.52.9/GT_CharacterInfo.asmx";
    }
    
    /// <remarks/>
    public event GetGameAccountCompletedEventHandler GetGameAccountCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGameAccount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Data.DataTable GetGameAccount(string strSTime, string strETime) {
        object[] results = this.Invoke("GetGameAccount", new object[] {
                    strSTime,
                    strETime});
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetGameAccount(string strSTime, string strETime, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetGameAccount", new object[] {
                    strSTime,
                    strETime}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Data.DataTable EndGetGameAccount(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public void GetGameAccountAsync(string strSTime, string strETime) {
        this.GetGameAccountAsync(strSTime, strETime, null);
    }
    
    /// <remarks/>
    public void GetGameAccountAsync(string strSTime, string strETime, object userState) {
        if ((this.GetGameAccountOperationCompleted == null)) {
            this.GetGameAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGameAccountOperationCompleted);
        }
        this.InvokeAsync("GetGameAccount", new object[] {
                    strSTime,
                    strETime}, this.GetGameAccountOperationCompleted, userState);
    }
    
    private void OnGetGameAccountOperationCompleted(object arg) {
        if ((this.GetGameAccountCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetGameAccountCompleted(this, new GetGameAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void GetGameAccountCompletedEventHandler(object sender, GetGameAccountCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetGameAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetGameAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Data.DataTable Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Data.DataTable)(this.results[0]));
        }
    }
}
