//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.1433
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此原始程式碼由 wsdl 版本=2.0.50727.42 自動產生。
// 
namespace HKGashService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceAccountSoap", Namespace="http://tempuri.org/")]
    public partial class ServiceAccount : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetCreateTimeOperationCompleted;
        
        /// <remarks/>
        public ServiceAccount() {
            this.Url = "https://www.gamania.com.hk/EventWS/serviceaccount.asmx";
        }
        
        /// <remarks/>
        public event GetCreateTimeCompletedEventHandler GetCreateTimeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCreateTime", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCreateTime(string strServiceAccount, string strServiceCode, string strServiceRegion) {
            object[] results = this.Invoke("GetCreateTime", new object[] {
                        strServiceAccount,
                        strServiceCode,
                        strServiceRegion});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetCreateTime(string strServiceAccount, string strServiceCode, string strServiceRegion, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetCreateTime", new object[] {
                        strServiceAccount,
                        strServiceCode,
                        strServiceRegion}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetCreateTime(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCreateTimeAsync(string strServiceAccount, string strServiceCode, string strServiceRegion) {
            this.GetCreateTimeAsync(strServiceAccount, strServiceCode, strServiceRegion, null);
        }
        
        /// <remarks/>
        public void GetCreateTimeAsync(string strServiceAccount, string strServiceCode, string strServiceRegion, object userState) {
            if ((this.GetCreateTimeOperationCompleted == null)) {
                this.GetCreateTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCreateTimeOperationCompleted);
            }
            this.InvokeAsync("GetCreateTime", new object[] {
                        strServiceAccount,
                        strServiceCode,
                        strServiceRegion}, this.GetCreateTimeOperationCompleted, userState);
        }
        
        private void OnGetCreateTimeOperationCompleted(object arg) {
            if ((this.GetCreateTimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCreateTimeCompleted(this, new GetCreateTimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetCreateTimeCompletedEventHandler(object sender, GetCreateTimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCreateTimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCreateTimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
